-- Root module for the Jacobian challenge project.
-- Units are added as they are completed.
import Jacobian.Init
import Jacobian.Surface
import Jacobian.LocalMultiplicity
import Jacobian.Forms
import Jacobian.MappingDegree
import Jacobian.ProjectiveLine
import Jacobian.ResidueCalculus
import Jacobian.Meromorphic
import Jacobian.Path
import Jacobian.SphereTopology
import Jacobian.MeromorphicTrace
import Jacobian.ProperDegree
import Jacobian.JacobianConstruction
import Jacobian.Cech
import Jacobian.Finiteness
import Jacobian.Dbar
import Jacobian.Monodromy
import Jacobian.FormTrace
import Jacobian.PlanarStokes
import Jacobian.SerrePairing
import Jacobian.AbelWeak
import Jacobian.DolbeaultComparison
import Jacobian.ResidueTheorem
import Jacobian.CanonicalForms
import Jacobian.LaurentTail
import Jacobian.JacFunctorial
import Jacobian.Abel
import Jacobian.TailDuality
import Jacobian.H1Genus
import Jacobian.RiemannRoch
import Jacobian.GenusSphereHeadline
